USE [master]
GO

/****** Object:  Database [TourismDB]    Script Date: 8/08/2024 2:23:24 a. m. ******/
CREATE DATABASE [TourismDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TourismDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TourismDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TourismDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TourismDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TourismDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TourismDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TourismDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TourismDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TourismDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TourismDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TourismDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TourismDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TourismDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TourismDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TourismDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TourismDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TourismDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TourismDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TourismDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TourismDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TourismDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TourismDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TourismDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TourismDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TourismDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TourismDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TourismDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TourismDB] SET RECOVERY FULL 
GO

ALTER DATABASE [TourismDB] SET  MULTI_USER 
GO

ALTER DATABASE [TourismDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TourismDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TourismDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TourismDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TourismDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TourismDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TourismDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TourismDB] SET  READ_WRITE 
GO


